# Generated by Django 5.0.6 on 2024-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='RoadSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/roadsign')),
                ('video', models.FileField(upload_to='videos')),
                ('audio', models.FileField(upload_to='audio')),
                ('dock', models.FileField(upload_to='dock')),
            ],
            options={
                'db_table': 'roadsigns',
            },
        ),
    ]
