# Generated by Django 5.0.6 on 2024-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_remove_roadsigns_dock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsigns',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='roadsigns',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
